/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'admin-grades-show-grades': RouteRecordInfo<'admin-grades-show-grades', '/admin/grades/show-grades', Record<never, never>, Record<never, never>>,
    'admin-study-years-show-study-years': RouteRecordInfo<'admin-study-years-show-study-years', '/admin/study-years/show-study-years', Record<never, never>, Record<never, never>>,
    'admin-subscription-packages-show-subscription-packages': RouteRecordInfo<'admin-subscription-packages-show-subscription-packages', '/admin/subscription-packages/show-subscription-packages', Record<never, never>, Record<never, never>>,
    'front-pages-checkout': RouteRecordInfo<'front-pages-checkout', '/front-pages/checkout', Record<never, never>, Record<never, never>>,
    'front-pages-help-center': RouteRecordInfo<'front-pages-help-center', '/front-pages/help-center', Record<never, never>, Record<never, never>>,
    'front-pages-help-center-article-title': RouteRecordInfo<'front-pages-help-center-article-title', '/front-pages/help-center/article/:title', { title: ParamValue<true> }, { title: ParamValue<false> }>,
    'front-pages-landing-page': RouteRecordInfo<'front-pages-landing-page', '/front-pages/landing-page', Record<never, never>, Record<never, never>>,
    'front-pages-payment': RouteRecordInfo<'front-pages-payment', '/front-pages/payment', Record<never, never>, Record<never, never>>,
    'front-pages-pricing': RouteRecordInfo<'front-pages-pricing', '/front-pages/pricing', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'student-dashboard': RouteRecordInfo<'student-dashboard', '/student/dashboard', Record<never, never>, Record<never, never>>,
    'student-profile-setup': RouteRecordInfo<'student-profile-setup', '/student/profile-setup', Record<never, never>, Record<never, never>>,
    'teacher-assignments-assignment-overview': RouteRecordInfo<'teacher-assignments-assignment-overview', '/teacher/assignments/assignment-overview', Record<never, never>, Record<never, never>>,
    'teacher-assignments-manage-assignments': RouteRecordInfo<'teacher-assignments-manage-assignments', '/teacher/assignments/manage-assignments', Record<never, never>, Record<never, never>>,
    'teacher-billing-pricing': RouteRecordInfo<'teacher-billing-pricing', '/teacher/billing/pricing', Record<never, never>, Record<never, never>>,
    'teacher-bookings-show-bookings': RouteRecordInfo<'teacher-bookings-show-bookings', '/teacher/bookings/show-bookings', Record<never, never>, Record<never, never>>,
    'teacher-course-show-course': RouteRecordInfo<'teacher-course-show-course', '/teacher/course/show-course', Record<never, never>, Record<never, never>>,
    'teacher-dashboard': RouteRecordInfo<'teacher-dashboard', '/teacher/dashboard', Record<never, never>, Record<never, never>>,
    'teacher-evaluations-bulk-upsert-evaluations': RouteRecordInfo<'teacher-evaluations-bulk-upsert-evaluations', '/teacher/evaluations/bulk-upsert-evaluations', Record<never, never>, Record<never, never>>,
    'teacher-evaluations-manage-evaluations': RouteRecordInfo<'teacher-evaluations-manage-evaluations', '/teacher/evaluations/manage-evaluations', Record<never, never>, Record<never, never>>,
    'teacher-exams-exam-details': RouteRecordInfo<'teacher-exams-exam-details', '/teacher/exams/exam-details', Record<never, never>, Record<never, never>>,
    'teacher-exams-manage-exams': RouteRecordInfo<'teacher-exams-manage-exams', '/teacher/exams/manage-exams', Record<never, never>, Record<never, never>>,
    'teacher-expenses-manage-expenses': RouteRecordInfo<'teacher-expenses-manage-expenses', '/teacher/expenses/manage-expenses', Record<never, never>, Record<never, never>>,
    'teacher-invoices-invoice-id': RouteRecordInfo<'teacher-invoices-invoice-id', '/teacher/invoices/:invoiceId', { invoiceId: ParamValue<true> }, { invoiceId: ParamValue<false> }>,
    'teacher-invoices-create-invoice': RouteRecordInfo<'teacher-invoices-create-invoice', '/teacher/invoices/create-invoice', Record<never, never>, Record<never, never>>,
    'teacher-invoices-edit-invoice-id': RouteRecordInfo<'teacher-invoices-edit-invoice-id', '/teacher/invoices/edit/:invoiceId', { invoiceId: ParamValue<true> }, { invoiceId: ParamValue<false> }>,
    'teacher-invoices-manage-invoices': RouteRecordInfo<'teacher-invoices-manage-invoices', '/teacher/invoices/manage-invoices', Record<never, never>, Record<never, never>>,
    'teacher-notifications-show-notifications': RouteRecordInfo<'teacher-notifications-show-notifications', '/teacher/notifications/show-notifications', Record<never, never>, Record<never, never>>,
    'teacher-payments-reservations-booking-id': RouteRecordInfo<'teacher-payments-reservations-booking-id', '/teacher/payments/reservations/:bookingId', { bookingId: ParamValue<true> }, { bookingId: ParamValue<false> }>,
    'teacher-payments-reservations-report': RouteRecordInfo<'teacher-payments-reservations-report', '/teacher/payments/reservations/report', Record<never, never>, Record<never, never>>,
    'teacher-payments-reservations-show-reservation-payments': RouteRecordInfo<'teacher-payments-reservations-show-reservation-payments', '/teacher/payments/reservations/show-reservation-payments', Record<never, never>, Record<never, never>>,
    'teacher-profile-setup': RouteRecordInfo<'teacher-profile-setup', '/teacher/profile-setup', Record<never, never>, Record<never, never>>,
    'teacher-reports-financial': RouteRecordInfo<'teacher-reports-financial', '/teacher/reports/financial', Record<never, never>, Record<never, never>>,
    'teacher-sessions-attendance-id': RouteRecordInfo<'teacher-sessions-attendance-id', '/teacher/sessions/attendance/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'teacher-sessions-manage-sessions': RouteRecordInfo<'teacher-sessions-manage-sessions', '/teacher/sessions/manage-sessions', Record<never, never>, Record<never, never>>,
    'teacher-subjects-show-subjects': RouteRecordInfo<'teacher-subjects-show-subjects', '/teacher/subjects/show-subjects', Record<never, never>, Record<never, never>>,
  }
}
